### ISSUE TITLE
Error on EC2().describeInstancesSync

### ISSUE THREAD

**Issue by orlade** [peerlibrary/meteor-aws-sdk#20]
`new AWS.EC2({region: 'ap-southeast-2'}).describeInstancesSync()` fails for me with the error:

```
W20150903-14:33:22.817(10)? (STDERR) ConfigError: Missing region in config
W20150903-14:33:22.817(10)? (STDERR)     at Object.Future.wait (C:\Users\Oliver\AppData\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:395:16)
W20150903-14:33:22.817(10)? (STDERR)     at [object Object].f [as describeInstancesSync] (packages/peerlibrary:blocking/server.js:18:1)
W20150903-14:33:22.818(10)? (STDERR)     at Object.EC2Service.sync (common\services/EC2Service.coffee:9:30)
W20150903-14:33:22.818(10)? (STDERR)     at Object.AwsSync.sync (server/AwsSync.coffee:10:16)
W20150903-14:33:22.818(10)? (STDERR)     at AwsSync.sync (server/AwsSync.coffee:5:11)
W20150903-14:33:22.818(10)? (STDERR)     at C:\dev\workspace\cortex\.meteor\local\build\programs\server\boot.js:229:5
W20150903-14:33:22.818(10)? (STDERR)     - - - - -
W20150903-14:33:22.818(10)? (STDERR)     at Request.VALIDATE_REGION (C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\event_listeners.js:81:45)
W20150903-14:33:22.818(10)? (STDERR)     at Request.callListeners (C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
W20150903-14:33:22.818(10)? (STDERR)     at callNextListener (C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\sequential_executor.js:95:12)
W20150903-14:33:22.818(10)? (STDERR)     at C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\event_listeners.js:75:9
W20150903-14:33:22.818(10)? (STDERR)     at finish (C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\config.js:228:7)
W20150903-14:33:22.819(10)? (STDERR)     at C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\config.js:244:9
W20150903-14:33:22.819(10)? (STDERR)     at SharedIniFileCredentials.get (C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\credentials.js:126:7)
W20150903-14:33:22.819(10)? (STDERR)     at getAsyncCredentials (C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\config.js:238:24)
W20150903-14:33:22.819(10)? (STDERR)     at Config.getCredentials (C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\config.js:258:9)
W20150903-14:33:22.819(10)? (STDERR)     at Request.VALIDATE_CREDENTIALS (C:\Users\Oliver\AppData\Local\.meteor\packages\peerlibrary_aws-sdk\2.1.47_1\npm\node_modules\aws-sdk\lib\event_listeners.js:70:26)
```

`new AWS.EC2({region: 'ap-southeast-2'}).describeInstances()` (asynchronous) works just fine with the same configuration.

Windows 10, Meteor 1.1.0.2, latest `meteor-aws-sdk`. If relevant, `node` v0.12.7 and `npm` 2.11.3.

**Comment by mitar** [comment]
Interesting. No idea what exactly is happening here.

**Comment by orlade** [comment]
Huh. I didn't understand either, so I just went with the async API. Now I tried the sync API again and it worked fine. Sorry, false alarm! Maybe I'd misconfigured something else.
